---
- name: Converge
  hosts: all
  become: true
  vars:
    headscale_namespaces:
      - 'default'
  tasks:
    - name: "Include ckstevenson.headscale"
      include_role:
        name: "ckstevenson.headscale"
